### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by niklasp** [sachinchoolur/lightgallery.js#163]
Last commits are quite old and pull requests not being answered. Can I build a project on this today or will it die soon? Are there alternatives?

**Comment by develth** [comment]
Would nice to know before i invest the 149$ into a license.

**Comment by sachinchoolur** [comment]
Due to some personal issues, I was able to provide only limited support for some time. Apologize for the inconvenience. 
But, last week I left my full-time job to work on lightGallery and other side projects. 
Now I'm working actively on lightGallery and I'll do my best to keep this project up to date.

Thank you for your patience.

**Comment by niklasp** [comment]
Cool. @sachinchoolur i am waiting for the v2 release. Also need a OEM license, how much is it and where do i get it?

**Comment by sachinchoolur** [comment]
Hey @niklasp,
LightGallery 2.0 first preview is available - 
http://sachinchoolur.github.io/lightGallery/v2/
https://github.com/sachinchoolur/lightGallery#version-20-update

Regarding the OEM license, please shoot me an email at sachi77n@gmail.com
